# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snapchat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snapchat
pod 'Firebase/Core'

  target 'snapchatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'snapchatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
